using backend.main.infrastructure.database.core;
using backend.main.features.events.search;
using backend.main.features.profile;
using backend.main.features.events;

using Microsoft.EntityFrameworkCore;

namespace backend.main.seeders
{
    public sealed class MockEventSeeder : ISeeder
    {
        private readonly AppDatabaseContext _dbContext;
        private readonly IEventSearchOutboxWriter _outboxWriter;
        private readonly ILogger<MockEventSeeder> _logger;

        public MockEventSeeder(
            AppDatabaseContext dbContext,
            IEventSearchOutboxWriter outboxWriter,
            ILogger<MockEventSeeder> logger
        )
        {
            _dbContext = dbContext;
            _outboxWriter = outboxWriter;
            _logger = logger;
        }

        public async Task SeedAsync(CancellationToken cancellationToken = default)
        {
            var seedEvents = BuildSeedEvents();
            var clubNames = seedEvents
                .Select(@event => @event.ClubName)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            var clubs = await _dbContext.Clubs
                .Where(club => clubNames.Contains(club.Name))
                .ToListAsync(cancellationToken);
            var clubLookup = clubs.ToDictionary(club => club.Name, StringComparer.OrdinalIgnoreCase);

            var missingClubs = clubNames
                .Where(name => !clubLookup.ContainsKey(name))
                .ToList();

            if (missingClubs.Count > 0)
            {
                _logger.LogWarning(
                    "[Seeders] Skipping mock events because required clubs are missing: {ClubNames}",
                    string.Join(", ", missingClubs)
                );
                return;
            }

            var targetClubIds = clubLookup.Values
                .Select(club => club.Id)
                .Distinct()
                .ToList();
            var seedEventNames = seedEvents
                .Select(@event => @event.Name)
                .ToList();

            var existingEvents = await _dbContext.Events
                .Where(@event => targetClubIds.Contains(@event.ClubId) && seedEventNames.Contains(@event.Name))
                .Select(@event => new { @event.ClubId, @event.Name })
                .ToListAsync(cancellationToken);

            var existingEventKeys = existingEvents
                .Select(@event => EventKey(@event.ClubId, @event.Name))
                .ToHashSet(StringComparer.OrdinalIgnoreCase);

            var missingEvents = new List<Events>();

            foreach (var seedEvent in seedEvents)
            {
                var club = clubLookup[seedEvent.ClubName];
                var eventKey = EventKey(club.Id, seedEvent.Name);

                if (existingEventKeys.Contains(eventKey))
                    continue;

                missingEvents.Add(new Events
                {
                    Name = seedEvent.Name,
                    Description = seedEvent.Description,
                    Location = seedEvent.Location,
                    isPrivate = seedEvent.IsPrivate,
                    maxParticipants = seedEvent.MaxParticipants,
                    registerCost = seedEvent.RegisterCost,
                    StartTime = seedEvent.StartTimeUtc,
                    EndTime = seedEvent.EndTimeUtc,
                    ClubId = club.Id,
                    Category = seedEvent.Category,
                    VenueName = seedEvent.VenueName,
                    City = seedEvent.City,
                    Latitude = seedEvent.Latitude,
                    Longitude = seedEvent.Longitude,
                    Tags = seedEvent.Tags.ToList(),
                    CreatedAt = seedEvent.CreatedAtUtc,
                    UpdatedAt = seedEvent.UpdatedAtUtc
                });
            }

            if (missingEvents.Count == 0)
            {
                _logger.LogInformation("[Seeders] Mock events already present. No new events added.");
                return;
            }

            var executionStrategy = _dbContext.Database.CreateExecutionStrategy();

            await executionStrategy.ExecuteAsync(async () =>
            {
                await using var transaction = await _dbContext.Database.BeginTransactionAsync(cancellationToken);

                await _dbContext.Events.AddRangeAsync(missingEvents, cancellationToken);
                await _dbContext.SaveChangesAsync(cancellationToken);

                foreach (var ev in missingEvents)
                    _outboxWriter.StageUpsert(ev);

                await RefreshClubEventCountsAsync(targetClubIds, cancellationToken);
                await _dbContext.SaveChangesAsync(cancellationToken);
                await transaction.CommitAsync(cancellationToken);
            });

            _logger.LogInformation(
                "[Seeders] Seeded {Count} mock event records.",
                missingEvents.Count
            );
        }

        private async Task RefreshClubEventCountsAsync(
            IReadOnlyCollection<int> clubIds,
            CancellationToken cancellationToken
        )
        {
            if (clubIds.Count == 0)
                return;

            var now = DateTime.UtcNow;

            var eventCounts = await _dbContext.Events
                .Where(@event => clubIds.Contains(@event.ClubId))
                .GroupBy(@event => @event.ClubId)
                .Select(group => new
                {
                    ClubId = group.Key,
                    EventCount = group.Count(),
                    AvailableEventCount = group.Count(@event => @event.EndTime == null || @event.EndTime > now)
                })
                .ToListAsync(cancellationToken);

            var countLookup = eventCounts.ToDictionary(count => count.ClubId);
            var clubs = await _dbContext.Clubs
                .Where(club => clubIds.Contains(club.Id))
                .ToListAsync(cancellationToken);

            foreach (var club in clubs)
            {
                if (countLookup.TryGetValue(club.Id, out var counts))
                {
                    club.EventCount = counts.EventCount;
                    club.AvaliableEventCount = counts.AvailableEventCount;
                }
                else
                {
                    club.EventCount = 0;
                    club.AvaliableEventCount = 0;
                }

                club.UpdatedAt = DateTime.UtcNow;
            }
        }

        private static List<SeedEventDefinition> BuildSeedEvents()
        {
            var now = DateTime.UtcNow;

            return
            [
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Sunrise 5K Training Loop",
                    "A paced beginner-friendly run along the lake with coffee after the cooldown stretch.",
                    "Queens Quay Trailhead",
                    false,
                    60,
                    0,
                    now.AddDays(2).Date.AddHours(11),
                    now.AddDays(2).Date.AddHours(13),
                    EventCategory.Fitness,
                    "Harbourfront Trail",
                    "Toronto",
                    43.6387,
                    -79.3817,
                    ["running", "fitness", "beginner"],
                    now.AddDays(-2),
                    now.AddDays(-1)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Waterfront Recovery Stretch",
                    "A relaxed mobility session for runners and walkers with guided stretching and breathwork.",
                    "Harbour Square Park",
                    false,
                    35,
                    0,
                    now.AddDays(0).Date.AddHours(3),
                    now.AddDays(0).Date.AddHours(4),
                    EventCategory.Fitness,
                    "Harbour Square Park",
                    "Toronto",
                    43.6405,
                    -79.3808,
                    ["stretch", "recovery", "wellness"],
                    now.AddDays(-1),
                    now.AddDays(0)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Founder Pitch Night",
                    "Short startup pitches, live feedback from mentors, and open networking for early builders.",
                    "Innovation Hall",
                    false,
                    120,
                    0,
                    now.AddDays(4).Date.AddHours(23),
                    now.AddDays(5).Date.AddHours(1),
                    EventCategory.Networking,
                    "Innovation Hall",
                    "Toronto",
                    43.6629,
                    -79.3957,
                    ["startup", "pitch", "networking"],
                    now.AddDays(-4),
                    now.AddDays(-2)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Product Jam Workshop",
                    "A hands-on product sprint covering idea framing, lightweight validation, and demo critiques.",
                    "Campus Design Lab",
                    false,
                    45,
                    0,
                    now.AddDays(7).Date.AddHours(17),
                    now.AddDays(7).Date.AddHours(20),
                    EventCategory.Workshop,
                    "Design Lab 204",
                    "Toronto",
                    43.6644,
                    -79.3982,
                    ["product", "workshop", "design"],
                    now.AddDays(-3),
                    now.AddDays(-1)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Spring Rooftop Mixer",
                    "Music, casual conversation, and light snacks for anyone looking to meet new people in the city.",
                    "King Street Rooftop",
                    false,
                    90,
                    0,
                    now.AddDays(5).Date.AddHours(23),
                    now.AddDays(6).Date.AddHours(2),
                    EventCategory.Social,
                    "Lantern House Rooftop",
                    "Toronto",
                    43.6459,
                    -79.3925,
                    ["social", "mixer", "city-life"],
                    now.AddDays(-5),
                    now.AddDays(-2)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Lakeside Interval Session #1",
                    "Speed intervals and form drills for runners preparing for spring races.",
                    "Martin Goodman Trail",
                    true,
                    25,
                    10,
                    now.AddDays(8).Date.AddHours(10),
                    now.AddDays(8).Date.AddHours(12),
                    EventCategory.Fitness,
                    "Harbourfront Trail",
                    "Toronto",
                    43.6387,
                    -79.3817,
                    ["running", "intervals", "cardio"],
                    now.AddDays(-20),
                    now.AddDays(-19)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Beginner Run Clinic #2",
                    "A no-pressure clinic covering pacing, warmups, and safe distance building.",
                    "Coronation Park",
                    false,
                    35,
                    0,
                    now.AddDays(9).Date.AddHours(11),
                    now.AddDays(9).Date.AddHours(13),
                    EventCategory.Fitness,
                    "Coronation Park Track",
                    "Toronto",
                    43.6397,
                    -79.3827,
                    ["running", "beginner", "clinic"],
                    now.AddDays(-19),
                    now.AddDays(-18)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Community Long Run #3",
                    "A conversational weekend long run with distance options for different paces.",
                    "Ontario Place West Gate",
                    false,
                    45,
                    0,
                    now.AddDays(10).Date.AddHours(12),
                    now.AddDays(10).Date.AddHours(14),
                    EventCategory.Fitness,
                    "Ontario Place Loop",
                    "Toronto",
                    43.6407,
                    -79.3837,
                    ["running", "long-run", "community"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Trail Strength Circuit #4",
                    "Outdoor bodyweight circuits focused on glutes, core stability, and injury prevention.",
                    "Trillium Park",
                    false,
                    55,
                    0,
                    now.AddDays(11).Date.AddHours(13),
                    now.AddDays(11).Date.AddHours(15),
                    EventCategory.Fitness,
                    "Trillium Park Lawn",
                    "Toronto",
                    43.6417,
                    -79.3847,
                    ["strength", "fitness", "outdoor"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Evening Tempo Run #5",
                    "A steady tempo workout designed for runners who want to build endurance.",
                    "Bathurst Quay",
                    false,
                    65,
                    0,
                    now.AddDays(12).Date.AddHours(14),
                    now.AddDays(12).Date.AddHours(16),
                    EventCategory.Fitness,
                    "Bathurst Quay Start",
                    "Toronto",
                    43.6427,
                    -79.3857,
                    ["running", "tempo", "endurance"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Yoga for Runners #6",
                    "Mobility yoga focused on hips, calves, hamstrings, and post-run recovery.",
                    "Waterfront Studio",
                    false,
                    75,
                    10,
                    now.AddDays(13).Date.AddHours(15),
                    now.AddDays(13).Date.AddHours(17),
                    EventCategory.Fitness,
                    "Waterfront Wellness Studio",
                    "Toronto",
                    43.6437,
                    -79.3867,
                    ["yoga", "recovery", "mobility"],
                    now.AddDays(-15),
                    now.AddDays(-14)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Charity Fun Run #7",
                    "A casual fundraising run with optional 3K and 5K routes.",
                    "HTO Park",
                    false,
                    85,
                    0,
                    now.AddDays(14).Date.AddHours(16),
                    now.AddDays(14).Date.AddHours(18),
                    EventCategory.Fitness,
                    "HTO Park Stage",
                    "Toronto",
                    43.6447,
                    -79.3817,
                    ["charity", "running", "social"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Hill Repeats Practice #8",
                    "Short hill repeats with coaching on posture, effort, and recovery.",
                    "Riverdale Park East",
                    false,
                    95,
                    0,
                    now.AddDays(15).Date.AddHours(17),
                    now.AddDays(15).Date.AddHours(19),
                    EventCategory.Fitness,
                    "Riverdale Hillside",
                    "Toronto",
                    43.6387,
                    -79.3827,
                    ["running", "hills", "training"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Morning Bootcamp #9",
                    "A high-energy bootcamp mixing cardio stations, kettlebells, and core work.",
                    "Roundhouse Park",
                    false,
                    25,
                    0,
                    now.AddDays(16).Date.AddHours(18),
                    now.AddDays(16).Date.AddHours(20),
                    EventCategory.Fitness,
                    "Roundhouse Green",
                    "Toronto",
                    43.6397,
                    -79.3837,
                    ["bootcamp", "cardio", "strength"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Run Club Social Walk #10",
                    "A low-intensity walk for new members who want to meet the group first.",
                    "Sugar Beach",
                    false,
                    35,
                    0,
                    now.AddDays(17).Date.AddHours(10),
                    now.AddDays(17).Date.AddHours(12),
                    EventCategory.Fitness,
                    "Sugar Beach Plaza",
                    "Toronto",
                    43.6407,
                    -79.3847,
                    ["walking", "social", "beginner"],
                    now.AddDays(-11),
                    now.AddDays(-10)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Lakeside Interval Session #11",
                    "Speed intervals and form drills for runners preparing for spring races.",
                    "Martin Goodman Trail",
                    false,
                    45,
                    10,
                    now.AddDays(18).Date.AddHours(11),
                    now.AddDays(18).Date.AddHours(13),
                    EventCategory.Fitness,
                    "Harbourfront Trail",
                    "Toronto",
                    43.6417,
                    -79.3857,
                    ["running", "intervals", "cardio"],
                    now.AddDays(-20),
                    now.AddDays(-19)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Beginner Run Clinic #12",
                    "A no-pressure clinic covering pacing, warmups, and safe distance building.",
                    "Coronation Park",
                    false,
                    55,
                    0,
                    now.AddDays(19).Date.AddHours(12),
                    now.AddDays(19).Date.AddHours(14),
                    EventCategory.Fitness,
                    "Coronation Park Track",
                    "Toronto",
                    43.6427,
                    -79.3867,
                    ["running", "beginner", "clinic"],
                    now.AddDays(-19),
                    now.AddDays(-18)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Community Long Run #13",
                    "A conversational weekend long run with distance options for different paces.",
                    "Ontario Place West Gate",
                    false,
                    65,
                    0,
                    now.AddDays(20).Date.AddHours(13),
                    now.AddDays(20).Date.AddHours(15),
                    EventCategory.Fitness,
                    "Ontario Place Loop",
                    "Toronto",
                    43.6437,
                    -79.3817,
                    ["running", "long-run", "community"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Trail Strength Circuit #14",
                    "Outdoor bodyweight circuits focused on glutes, core stability, and injury prevention.",
                    "Trillium Park",
                    true,
                    75,
                    0,
                    now.AddDays(21).Date.AddHours(14),
                    now.AddDays(21).Date.AddHours(16),
                    EventCategory.Fitness,
                    "Trillium Park Lawn",
                    "Toronto",
                    43.6447,
                    -79.3827,
                    ["strength", "fitness", "outdoor"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Evening Tempo Run #15",
                    "A steady tempo workout designed for runners who want to build endurance.",
                    "Bathurst Quay",
                    false,
                    85,
                    0,
                    now.AddDays(22).Date.AddHours(15),
                    now.AddDays(22).Date.AddHours(17),
                    EventCategory.Fitness,
                    "Bathurst Quay Start",
                    "Toronto",
                    43.6387,
                    -79.3837,
                    ["running", "tempo", "endurance"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Yoga for Runners #16",
                    "Mobility yoga focused on hips, calves, hamstrings, and post-run recovery.",
                    "Waterfront Studio",
                    false,
                    95,
                    10,
                    now.AddDays(23).Date.AddHours(16),
                    now.AddDays(23).Date.AddHours(18),
                    EventCategory.Fitness,
                    "Waterfront Wellness Studio",
                    "Toronto",
                    43.6397,
                    -79.3847,
                    ["yoga", "recovery", "mobility"],
                    now.AddDays(-15),
                    now.AddDays(-14)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Charity Fun Run #17",
                    "A casual fundraising run with optional 3K and 5K routes.",
                    "HTO Park",
                    false,
                    25,
                    0,
                    now.AddDays(24).Date.AddHours(17),
                    now.AddDays(24).Date.AddHours(19),
                    EventCategory.Fitness,
                    "HTO Park Stage",
                    "Toronto",
                    43.6407,
                    -79.3857,
                    ["charity", "running", "social"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Hill Repeats Practice #18",
                    "Short hill repeats with coaching on posture, effort, and recovery.",
                    "Riverdale Park East",
                    false,
                    35,
                    0,
                    now.AddDays(25).Date.AddHours(18),
                    now.AddDays(25).Date.AddHours(20),
                    EventCategory.Fitness,
                    "Riverdale Hillside",
                    "Toronto",
                    43.6417,
                    -79.3867,
                    ["running", "hills", "training"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Morning Bootcamp #19",
                    "A high-energy bootcamp mixing cardio stations, kettlebells, and core work.",
                    "Roundhouse Park",
                    false,
                    45,
                    0,
                    now.AddDays(26).Date.AddHours(10),
                    now.AddDays(26).Date.AddHours(12),
                    EventCategory.Fitness,
                    "Roundhouse Green",
                    "Toronto",
                    43.6427,
                    -79.3817,
                    ["bootcamp", "cardio", "strength"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Run Club Social Walk #20",
                    "A low-intensity walk for new members who want to meet the group first.",
                    "Sugar Beach",
                    false,
                    55,
                    0,
                    now.AddDays(27).Date.AddHours(11),
                    now.AddDays(27).Date.AddHours(13),
                    EventCategory.Fitness,
                    "Sugar Beach Plaza",
                    "Toronto",
                    43.6437,
                    -79.3827,
                    ["walking", "social", "beginner"],
                    now.AddDays(-11),
                    now.AddDays(-10)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Lakeside Interval Session #21",
                    "Speed intervals and form drills for runners preparing for spring races.",
                    "Martin Goodman Trail",
                    false,
                    65,
                    10,
                    now.AddDays(28).Date.AddHours(12),
                    now.AddDays(28).Date.AddHours(14),
                    EventCategory.Fitness,
                    "Harbourfront Trail",
                    "Toronto",
                    43.6447,
                    -79.3837,
                    ["running", "intervals", "cardio"],
                    now.AddDays(-20),
                    now.AddDays(-19)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Beginner Run Clinic #22",
                    "A no-pressure clinic covering pacing, warmups, and safe distance building.",
                    "Coronation Park",
                    false,
                    75,
                    0,
                    now.AddDays(29).Date.AddHours(13),
                    now.AddDays(29).Date.AddHours(15),
                    EventCategory.Fitness,
                    "Coronation Park Track",
                    "Toronto",
                    43.6387,
                    -79.3847,
                    ["running", "beginner", "clinic"],
                    now.AddDays(-19),
                    now.AddDays(-18)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Community Long Run #23",
                    "A conversational weekend long run with distance options for different paces.",
                    "Ontario Place West Gate",
                    false,
                    85,
                    0,
                    now.AddDays(30).Date.AddHours(14),
                    now.AddDays(30).Date.AddHours(16),
                    EventCategory.Fitness,
                    "Ontario Place Loop",
                    "Toronto",
                    43.6397,
                    -79.3857,
                    ["running", "long-run", "community"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Trail Strength Circuit #24",
                    "Outdoor bodyweight circuits focused on glutes, core stability, and injury prevention.",
                    "Trillium Park",
                    false,
                    95,
                    0,
                    now.AddDays(31).Date.AddHours(15),
                    now.AddDays(31).Date.AddHours(17),
                    EventCategory.Fitness,
                    "Trillium Park Lawn",
                    "Toronto",
                    43.6407,
                    -79.3867,
                    ["strength", "fitness", "outdoor"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "Harbour Runners Club",
                    "Evening Tempo Run #25",
                    "A steady tempo workout designed for runners who want to build endurance.",
                    "Bathurst Quay",
                    false,
                    25,
                    0,
                    now.AddDays(32).Date.AddHours(16),
                    now.AddDays(32).Date.AddHours(18),
                    EventCategory.Fitness,
                    "Bathurst Quay Start",
                    "Toronto",
                    43.6417,
                    -79.3817,
                    ["running", "tempo", "endurance"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "MVP Build Sprint #1",
                    "A guided workshop for turning rough ideas into a small testable product.",
                    "Campus Design Lab",
                    true,
                    30,
                    15,
                    now.AddDays(12).Date.AddHours(13),
                    now.AddDays(12).Date.AddHours(16),
                    EventCategory.Workshop,
                    "Design Lab 204",
                    "Toronto",
                    43.6629,
                    -79.3957,
                    ["mvp", "product", "workshop"],
                    now.AddDays(-25),
                    now.AddDays(-24)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "API Design Lab #2",
                    "A practical session on designing reliable APIs, versioning, and error contracts.",
                    "Engineering Commons",
                    false,
                    38,
                    0,
                    now.AddDays(13).Date.AddHours(14),
                    now.AddDays(13).Date.AddHours(17),
                    EventCategory.Workshop,
                    "Engineering Commons 301",
                    "Toronto",
                    43.6641,
                    -79.3969,
                    ["api", "backend", "workshop"],
                    now.AddDays(-24),
                    now.AddDays(-23)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Portfolio Review Night #3",
                    "Peer and mentor reviews for resumes, portfolios, GitHub profiles, and demos.",
                    "Career Studio",
                    false,
                    46,
                    0,
                    now.AddDays(14).Date.AddHours(15),
                    now.AddDays(14).Date.AddHours(18),
                    EventCategory.Workshop,
                    "Career Studio A",
                    "Toronto",
                    43.6653,
                    -79.3981,
                    ["career", "portfolio", "feedback"],
                    now.AddDays(-23),
                    now.AddDays(-22)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Design Systems Workshop #4",
                    "Hands-on exercises for reusable components, tokens, and accessible UI patterns.",
                    "UX Studio",
                    false,
                    54,
                    0,
                    now.AddDays(15).Date.AddHours(16),
                    now.AddDays(15).Date.AddHours(19),
                    EventCategory.Workshop,
                    "UX Studio 2",
                    "Toronto",
                    43.6665,
                    -79.3993,
                    ["design-system", "frontend", "accessibility"],
                    now.AddDays(-22),
                    now.AddDays(-21)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "AI Product Prototyping #5",
                    "Build a lightweight AI-assisted product prototype and discuss responsible launch risks.",
                    "Innovation Hall",
                    false,
                    62,
                    15,
                    now.AddDays(16).Date.AddHours(17),
                    now.AddDays(16).Date.AddHours(20),
                    EventCategory.Workshop,
                    "Innovation Hall Lab",
                    "Toronto",
                    43.6677,
                    -79.3957,
                    ["ai", "prototype", "product"],
                    now.AddDays(-21),
                    now.AddDays(-20)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Cloud Deployment Clinic #6",
                    "Debug deployments, environment variables, Dockerfiles, and cloud service configs.",
                    "DevOps Room",
                    false,
                    70,
                    0,
                    now.AddDays(17).Date.AddHours(18),
                    now.AddDays(17).Date.AddHours(21),
                    EventCategory.Workshop,
                    "DevOps Room 112",
                    "Toronto",
                    43.6629,
                    -79.3969,
                    ["cloud", "docker", "devops"],
                    now.AddDays(-20),
                    now.AddDays(-19)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Data Modeling Workshop #7",
                    "Practice turning product requirements into normalized schemas and search indexes.",
                    "Database Lab",
                    false,
                    78,
                    0,
                    now.AddDays(18).Date.AddHours(19),
                    now.AddDays(18).Date.AddHours(22),
                    EventCategory.Workshop,
                    "Database Lab 3",
                    "Toronto",
                    43.6641,
                    -79.3981,
                    ["database", "modeling", "search"],
                    now.AddDays(-19),
                    now.AddDays(-18)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Hackathon Prep Session #8",
                    "Team formation, scope planning, and technical architecture tips before hackathon weekend.",
                    "Campus Design Lab",
                    false,
                    86,
                    0,
                    now.AddDays(19).Date.AddHours(20),
                    now.AddDays(19).Date.AddHours(23),
                    EventCategory.Workshop,
                    "Design Lab 102",
                    "Toronto",
                    43.6653,
                    -79.3993,
                    ["hackathon", "planning", "workshop"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Startup Legal Basics #9",
                    "A practical overview of incorporation, equity splits, contracts, and early risk areas.",
                    "Founder Lounge",
                    false,
                    94,
                    15,
                    now.AddDays(20).Date.AddHours(13),
                    now.AddDays(20).Date.AddHours(16),
                    EventCategory.Workshop,
                    "Founder Lounge",
                    "Toronto",
                    43.6665,
                    -79.3957,
                    ["startup", "legal", "founders"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "User Research Jam #10",
                    "Learn interview scripts, assumption mapping, and synthesis methods for product discovery.",
                    "Research Lab",
                    false,
                    102,
                    0,
                    now.AddDays(21).Date.AddHours(14),
                    now.AddDays(21).Date.AddHours(17),
                    EventCategory.Workshop,
                    "Research Lab B",
                    "Toronto",
                    43.6677,
                    -79.3969,
                    ["ux", "research", "discovery"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "MVP Build Sprint #11",
                    "A guided workshop for turning rough ideas into a small testable product.",
                    "Campus Design Lab",
                    false,
                    30,
                    0,
                    now.AddDays(22).Date.AddHours(15),
                    now.AddDays(22).Date.AddHours(18),
                    EventCategory.Workshop,
                    "Design Lab 204",
                    "Toronto",
                    43.6629,
                    -79.3981,
                    ["mvp", "product", "workshop"],
                    now.AddDays(-15),
                    now.AddDays(-14)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "API Design Lab #12",
                    "A practical session on designing reliable APIs, versioning, and error contracts.",
                    "Engineering Commons",
                    true,
                    38,
                    0,
                    now.AddDays(23).Date.AddHours(16),
                    now.AddDays(23).Date.AddHours(19),
                    EventCategory.Workshop,
                    "Engineering Commons 301",
                    "Toronto",
                    43.6641,
                    -79.3993,
                    ["api", "backend", "workshop"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Portfolio Review Night #13",
                    "Peer and mentor reviews for resumes, portfolios, GitHub profiles, and demos.",
                    "Career Studio",
                    false,
                    46,
                    15,
                    now.AddDays(24).Date.AddHours(17),
                    now.AddDays(24).Date.AddHours(20),
                    EventCategory.Workshop,
                    "Career Studio A",
                    "Toronto",
                    43.6653,
                    -79.3957,
                    ["career", "portfolio", "feedback"],
                    now.AddDays(-25),
                    now.AddDays(-24)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Design Systems Workshop #14",
                    "Hands-on exercises for reusable components, tokens, and accessible UI patterns.",
                    "UX Studio",
                    false,
                    54,
                    0,
                    now.AddDays(25).Date.AddHours(18),
                    now.AddDays(25).Date.AddHours(21),
                    EventCategory.Workshop,
                    "UX Studio 2",
                    "Toronto",
                    43.6665,
                    -79.3969,
                    ["design-system", "frontend", "accessibility"],
                    now.AddDays(-24),
                    now.AddDays(-23)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "AI Product Prototyping #15",
                    "Build a lightweight AI-assisted product prototype and discuss responsible launch risks.",
                    "Innovation Hall",
                    false,
                    62,
                    0,
                    now.AddDays(26).Date.AddHours(19),
                    now.AddDays(26).Date.AddHours(22),
                    EventCategory.Workshop,
                    "Innovation Hall Lab",
                    "Toronto",
                    43.6677,
                    -79.3981,
                    ["ai", "prototype", "product"],
                    now.AddDays(-23),
                    now.AddDays(-22)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Cloud Deployment Clinic #16",
                    "Debug deployments, environment variables, Dockerfiles, and cloud service configs.",
                    "DevOps Room",
                    false,
                    70,
                    0,
                    now.AddDays(27).Date.AddHours(20),
                    now.AddDays(27).Date.AddHours(23),
                    EventCategory.Workshop,
                    "DevOps Room 112",
                    "Toronto",
                    43.6629,
                    -79.3993,
                    ["cloud", "docker", "devops"],
                    now.AddDays(-22),
                    now.AddDays(-21)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Data Modeling Workshop #17",
                    "Practice turning product requirements into normalized schemas and search indexes.",
                    "Database Lab",
                    false,
                    78,
                    15,
                    now.AddDays(28).Date.AddHours(13),
                    now.AddDays(28).Date.AddHours(16),
                    EventCategory.Workshop,
                    "Database Lab 3",
                    "Toronto",
                    43.6641,
                    -79.3957,
                    ["database", "modeling", "search"],
                    now.AddDays(-21),
                    now.AddDays(-20)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Hackathon Prep Session #18",
                    "Team formation, scope planning, and technical architecture tips before hackathon weekend.",
                    "Campus Design Lab",
                    false,
                    86,
                    0,
                    now.AddDays(29).Date.AddHours(14),
                    now.AddDays(29).Date.AddHours(17),
                    EventCategory.Workshop,
                    "Design Lab 102",
                    "Toronto",
                    43.6653,
                    -79.3969,
                    ["hackathon", "planning", "workshop"],
                    now.AddDays(-20),
                    now.AddDays(-19)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Startup Legal Basics #19",
                    "A practical overview of incorporation, equity splits, contracts, and early risk areas.",
                    "Founder Lounge",
                    false,
                    94,
                    0,
                    now.AddDays(30).Date.AddHours(15),
                    now.AddDays(30).Date.AddHours(18),
                    EventCategory.Workshop,
                    "Founder Lounge",
                    "Toronto",
                    43.6665,
                    -79.3981,
                    ["startup", "legal", "founders"],
                    now.AddDays(-19),
                    now.AddDays(-18)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "User Research Jam #20",
                    "Learn interview scripts, assumption mapping, and synthesis methods for product discovery.",
                    "Research Lab",
                    false,
                    102,
                    0,
                    now.AddDays(31).Date.AddHours(16),
                    now.AddDays(31).Date.AddHours(19),
                    EventCategory.Workshop,
                    "Research Lab B",
                    "Toronto",
                    43.6677,
                    -79.3993,
                    ["ux", "research", "discovery"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "MVP Build Sprint #21",
                    "A guided workshop for turning rough ideas into a small testable product.",
                    "Campus Design Lab",
                    false,
                    30,
                    15,
                    now.AddDays(32).Date.AddHours(17),
                    now.AddDays(32).Date.AddHours(20),
                    EventCategory.Workshop,
                    "Design Lab 204",
                    "Toronto",
                    43.6629,
                    -79.3957,
                    ["mvp", "product", "workshop"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "API Design Lab #22",
                    "A practical session on designing reliable APIs, versioning, and error contracts.",
                    "Engineering Commons",
                    false,
                    38,
                    0,
                    now.AddDays(33).Date.AddHours(18),
                    now.AddDays(33).Date.AddHours(21),
                    EventCategory.Workshop,
                    "Engineering Commons 301",
                    "Toronto",
                    43.6641,
                    -79.3969,
                    ["api", "backend", "workshop"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Portfolio Review Night #23",
                    "Peer and mentor reviews for resumes, portfolios, GitHub profiles, and demos.",
                    "Career Studio",
                    true,
                    46,
                    0,
                    now.AddDays(34).Date.AddHours(19),
                    now.AddDays(34).Date.AddHours(22),
                    EventCategory.Workshop,
                    "Career Studio A",
                    "Toronto",
                    43.6653,
                    -79.3981,
                    ["career", "portfolio", "feedback"],
                    now.AddDays(-15),
                    now.AddDays(-14)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Design Systems Workshop #24",
                    "Hands-on exercises for reusable components, tokens, and accessible UI patterns.",
                    "UX Studio",
                    false,
                    54,
                    0,
                    now.AddDays(35).Date.AddHours(20),
                    now.AddDays(35).Date.AddHours(23),
                    EventCategory.Workshop,
                    "UX Studio 2",
                    "Toronto",
                    43.6665,
                    -79.3993,
                    ["design-system", "frontend", "accessibility"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "AI Product Prototyping #25",
                    "Build a lightweight AI-assisted product prototype and discuss responsible launch risks.",
                    "Innovation Hall",
                    false,
                    62,
                    15,
                    now.AddDays(36).Date.AddHours(13),
                    now.AddDays(36).Date.AddHours(16),
                    EventCategory.Workshop,
                    "Innovation Hall Lab",
                    "Toronto",
                    43.6677,
                    -79.3957,
                    ["ai", "prototype", "product"],
                    now.AddDays(-25),
                    now.AddDays(-24)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Tech Coffee Chats #1",
                    "Small-group coffee chats connecting students, founders, and engineers.",
                    "Innovation Cafe",
                    false,
                    50,
                    5,
                    now.AddDays(16).Date.AddHours(17),
                    now.AddDays(16).Date.AddHours(19),
                    EventCategory.Networking,
                    "Innovation Cafe",
                    "Toronto",
                    43.6620,
                    -79.3950,
                    ["networking", "coffee", "tech"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Investor Office Hours #2",
                    "Short mentor conversations for founders preparing fundraising narratives.",
                    "Founder Lounge",
                    false,
                    62,
                    0,
                    now.AddDays(17).Date.AddHours(18),
                    now.AddDays(17).Date.AddHours(20),
                    EventCategory.Networking,
                    "Founder Lounge",
                    "Toronto",
                    43.6630,
                    -79.3960,
                    ["startup", "investors", "mentorship"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Women in Tech Mixer #3",
                    "A welcoming mixer for students and professionals in software, product, and design.",
                    "Innovation Hall",
                    false,
                    74,
                    0,
                    now.AddDays(18).Date.AddHours(19),
                    now.AddDays(18).Date.AddHours(21),
                    EventCategory.Networking,
                    "Innovation Atrium",
                    "Toronto",
                    43.6640,
                    -79.3970,
                    ["networking", "women-in-tech", "community"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Backend Engineers Meetup #4",
                    "A casual meetup on APIs, distributed systems, observability, and reliability.",
                    "Engineering Commons",
                    false,
                    86,
                    5,
                    now.AddDays(19).Date.AddHours(20),
                    now.AddDays(19).Date.AddHours(22),
                    EventCategory.Networking,
                    "Engineering Commons Hall",
                    "Toronto",
                    43.6650,
                    -79.3980,
                    ["backend", "systems", "networking"],
                    now.AddDays(-15),
                    now.AddDays(-14)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Campus Founder Breakfast #5",
                    "Breakfast meetup for early-stage founders comparing traction, hiring, and product lessons.",
                    "Campus Cafe",
                    false,
                    98,
                    0,
                    now.AddDays(20).Date.AddHours(21),
                    now.AddDays(20).Date.AddHours(23),
                    EventCategory.Networking,
                    "Campus Cafe",
                    "Toronto",
                    43.6660,
                    -79.3990,
                    ["founders", "breakfast", "startup"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Alumni Demo Circle #6",
                    "Alumni builders share demos, lessons learned, and hiring advice.",
                    "Demo Theatre",
                    false,
                    110,
                    0,
                    now.AddDays(21).Date.AddHours(22),
                    now.AddDays(22).Date.AddHours(0),
                    EventCategory.Networking,
                    "Demo Theatre",
                    "Toronto",
                    43.6670,
                    -79.3950,
                    ["alumni", "demo", "networking"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Product Managers Roundtable #7",
                    "A moderated conversation on roadmaps, metrics, prioritization, and stakeholder tradeoffs.",
                    "Product Studio",
                    false,
                    122,
                    5,
                    now.AddDays(22).Date.AddHours(17),
                    now.AddDays(22).Date.AddHours(19),
                    EventCategory.Networking,
                    "Product Studio",
                    "Toronto",
                    43.6620,
                    -79.3960,
                    ["product", "roundtable", "networking"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Open Source Contributors Night #8",
                    "Meet maintainers, discuss first issues, and find projects to contribute to.",
                    "Collaboration Hub",
                    false,
                    134,
                    0,
                    now.AddDays(23).Date.AddHours(18),
                    now.AddDays(23).Date.AddHours(20),
                    EventCategory.Networking,
                    "Collaboration Hub",
                    "Toronto",
                    43.6630,
                    -79.3970,
                    ["open-source", "github", "community"],
                    now.AddDays(-11),
                    now.AddDays(-10)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Internship Stories Panel #9",
                    "Recent interns share interview prep, team matching, onboarding, and project lessons.",
                    "Lecture Hall B",
                    false,
                    146,
                    0,
                    now.AddDays(24).Date.AddHours(19),
                    now.AddDays(24).Date.AddHours(21),
                    EventCategory.Networking,
                    "Lecture Hall B",
                    "Toronto",
                    43.6640,
                    -79.3980,
                    ["internship", "panel", "career"],
                    now.AddDays(-10),
                    now.AddDays(-9)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Local Builders Social #10",
                    "An informal evening for builders to exchange ideas and find collaborators.",
                    "Innovation Hall",
                    false,
                    50,
                    5,
                    now.AddDays(25).Date.AddHours(20),
                    now.AddDays(25).Date.AddHours(22),
                    EventCategory.Networking,
                    "Innovation Atrium",
                    "Toronto",
                    43.6650,
                    -79.3990,
                    ["builders", "social", "networking"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Tech Coffee Chats #11",
                    "Small-group coffee chats connecting students, founders, and engineers.",
                    "Innovation Cafe",
                    false,
                    62,
                    0,
                    now.AddDays(26).Date.AddHours(21),
                    now.AddDays(26).Date.AddHours(23),
                    EventCategory.Networking,
                    "Innovation Cafe",
                    "Toronto",
                    43.6660,
                    -79.3950,
                    ["networking", "coffee", "tech"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Investor Office Hours #12",
                    "Short mentor conversations for founders preparing fundraising narratives.",
                    "Founder Lounge",
                    false,
                    74,
                    0,
                    now.AddDays(27).Date.AddHours(22),
                    now.AddDays(28).Date.AddHours(0),
                    EventCategory.Networking,
                    "Founder Lounge",
                    "Toronto",
                    43.6670,
                    -79.3960,
                    ["startup", "investors", "mentorship"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Women in Tech Mixer #13",
                    "A welcoming mixer for students and professionals in software, product, and design.",
                    "Innovation Hall",
                    false,
                    86,
                    5,
                    now.AddDays(28).Date.AddHours(17),
                    now.AddDays(28).Date.AddHours(19),
                    EventCategory.Networking,
                    "Innovation Atrium",
                    "Toronto",
                    43.6620,
                    -79.3970,
                    ["networking", "women-in-tech", "community"],
                    now.AddDays(-15),
                    now.AddDays(-14)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Backend Engineers Meetup #14",
                    "A casual meetup on APIs, distributed systems, observability, and reliability.",
                    "Engineering Commons",
                    false,
                    98,
                    0,
                    now.AddDays(29).Date.AddHours(18),
                    now.AddDays(29).Date.AddHours(20),
                    EventCategory.Networking,
                    "Engineering Commons Hall",
                    "Toronto",
                    43.6630,
                    -79.3980,
                    ["backend", "systems", "networking"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Campus Founder Breakfast #15",
                    "Breakfast meetup for early-stage founders comparing traction, hiring, and product lessons.",
                    "Campus Cafe",
                    false,
                    110,
                    0,
                    now.AddDays(30).Date.AddHours(19),
                    now.AddDays(30).Date.AddHours(21),
                    EventCategory.Networking,
                    "Campus Cafe",
                    "Toronto",
                    43.6640,
                    -79.3990,
                    ["founders", "breakfast", "startup"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Alumni Demo Circle #16",
                    "Alumni builders share demos, lessons learned, and hiring advice.",
                    "Demo Theatre",
                    false,
                    122,
                    5,
                    now.AddDays(31).Date.AddHours(20),
                    now.AddDays(31).Date.AddHours(22),
                    EventCategory.Networking,
                    "Demo Theatre",
                    "Toronto",
                    43.6650,
                    -79.3950,
                    ["alumni", "demo", "networking"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Product Managers Roundtable #17",
                    "A moderated conversation on roadmaps, metrics, prioritization, and stakeholder tradeoffs.",
                    "Product Studio",
                    false,
                    134,
                    0,
                    now.AddDays(32).Date.AddHours(21),
                    now.AddDays(32).Date.AddHours(23),
                    EventCategory.Networking,
                    "Product Studio",
                    "Toronto",
                    43.6660,
                    -79.3960,
                    ["product", "roundtable", "networking"],
                    now.AddDays(-11),
                    now.AddDays(-10)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Open Source Contributors Night #18",
                    "Meet maintainers, discuss first issues, and find projects to contribute to.",
                    "Collaboration Hub",
                    false,
                    146,
                    0,
                    now.AddDays(33).Date.AddHours(22),
                    now.AddDays(34).Date.AddHours(0),
                    EventCategory.Networking,
                    "Collaboration Hub",
                    "Toronto",
                    43.6670,
                    -79.3970,
                    ["open-source", "github", "community"],
                    now.AddDays(-10),
                    now.AddDays(-9)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Internship Stories Panel #19",
                    "Recent interns share interview prep, team matching, onboarding, and project lessons.",
                    "Lecture Hall B",
                    false,
                    50,
                    5,
                    now.AddDays(34).Date.AddHours(17),
                    now.AddDays(34).Date.AddHours(19),
                    EventCategory.Networking,
                    "Lecture Hall B",
                    "Toronto",
                    43.6620,
                    -79.3980,
                    ["internship", "panel", "career"],
                    now.AddDays(-18),
                    now.AddDays(-17)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Local Builders Social #20",
                    "An informal evening for builders to exchange ideas and find collaborators.",
                    "Innovation Hall",
                    false,
                    62,
                    0,
                    now.AddDays(35).Date.AddHours(18),
                    now.AddDays(35).Date.AddHours(20),
                    EventCategory.Networking,
                    "Innovation Atrium",
                    "Toronto",
                    43.6630,
                    -79.3990,
                    ["builders", "social", "networking"],
                    now.AddDays(-17),
                    now.AddDays(-16)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Tech Coffee Chats #21",
                    "Small-group coffee chats connecting students, founders, and engineers.",
                    "Innovation Cafe",
                    false,
                    74,
                    0,
                    now.AddDays(36).Date.AddHours(19),
                    now.AddDays(36).Date.AddHours(21),
                    EventCategory.Networking,
                    "Innovation Cafe",
                    "Toronto",
                    43.6640,
                    -79.3950,
                    ["networking", "coffee", "tech"],
                    now.AddDays(-16),
                    now.AddDays(-15)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Investor Office Hours #22",
                    "Short mentor conversations for founders preparing fundraising narratives.",
                    "Founder Lounge",
                    false,
                    86,
                    5,
                    now.AddDays(37).Date.AddHours(20),
                    now.AddDays(37).Date.AddHours(22),
                    EventCategory.Networking,
                    "Founder Lounge",
                    "Toronto",
                    43.6650,
                    -79.3960,
                    ["startup", "investors", "mentorship"],
                    now.AddDays(-15),
                    now.AddDays(-14)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Women in Tech Mixer #23",
                    "A welcoming mixer for students and professionals in software, product, and design.",
                    "Innovation Hall",
                    false,
                    98,
                    0,
                    now.AddDays(38).Date.AddHours(21),
                    now.AddDays(38).Date.AddHours(23),
                    EventCategory.Networking,
                    "Innovation Atrium",
                    "Toronto",
                    43.6660,
                    -79.3970,
                    ["networking", "women-in-tech", "community"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Backend Engineers Meetup #24",
                    "A casual meetup on APIs, distributed systems, observability, and reliability.",
                    "Engineering Commons",
                    false,
                    110,
                    0,
                    now.AddDays(39).Date.AddHours(22),
                    now.AddDays(40).Date.AddHours(0),
                    EventCategory.Networking,
                    "Engineering Commons Hall",
                    "Toronto",
                    43.6670,
                    -79.3980,
                    ["backend", "systems", "networking"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "North Campus Builders",
                    "Campus Founder Breakfast #25",
                    "Breakfast meetup for early-stage founders comparing traction, hiring, and product lessons.",
                    "Campus Cafe",
                    false,
                    122,
                    5,
                    now.AddDays(40).Date.AddHours(17),
                    now.AddDays(40).Date.AddHours(19),
                    EventCategory.Networking,
                    "Campus Cafe",
                    "Toronto",
                    43.6620,
                    -79.3990,
                    ["founders", "breakfast", "startup"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Board Game Social #1",
                    "A relaxed night of strategy games, party games, snacks, and new friends.",
                    "Lantern House",
                    true,
                    35,
                    8,
                    now.AddDays(20).Date.AddHours(18),
                    now.AddDays(20).Date.AddHours(21),
                    EventCategory.Social,
                    "Lantern House Lounge",
                    "Toronto",
                    43.6459,
                    -79.3925,
                    ["board-games", "social", "indoor"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Karaoke Night #2",
                    "Casual karaoke with group songs, themed rounds, and zero performance pressure.",
                    "Queen West Studio",
                    false,
                    45,
                    0,
                    now.AddDays(21).Date.AddHours(19),
                    now.AddDays(21).Date.AddHours(22),
                    EventCategory.Social,
                    "Queen West Studio",
                    "Toronto",
                    43.6474,
                    -79.3938,
                    ["karaoke", "music", "social"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Photo Walk Meetup #3",
                    "Explore downtown photo spots with prompts for portraits, street scenes, and architecture.",
                    "Nathan Phillips Square",
                    false,
                    55,
                    0,
                    now.AddDays(22).Date.AddHours(20),
                    now.AddDays(22).Date.AddHours(23),
                    EventCategory.Social,
                    "City Hall Plaza",
                    "Toronto",
                    43.6489,
                    -79.3951,
                    ["photography", "walk", "social"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Trivia and Tacos #4",
                    "Team trivia with food, prizes, and rotating categories from movies to tech.",
                    "King Street Loft",
                    false,
                    65,
                    0,
                    now.AddDays(23).Date.AddHours(21),
                    now.AddDays(24).Date.AddHours(0),
                    EventCategory.Social,
                    "King Street Loft",
                    "Toronto",
                    43.6504,
                    -79.3964,
                    ["trivia", "food", "social"],
                    now.AddDays(-11),
                    now.AddDays(-10)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Newcomer Welcome Night #5",
                    "A friendly welcome event for anyone new to the city or the community.",
                    "Lantern House",
                    false,
                    75,
                    8,
                    now.AddDays(24).Date.AddHours(22),
                    now.AddDays(25).Date.AddHours(1),
                    EventCategory.Social,
                    "Lantern House Lounge",
                    "Toronto",
                    43.6519,
                    -79.3977,
                    ["newcomer", "welcome", "social"],
                    now.AddDays(-10),
                    now.AddDays(-9)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Art Market Hangout #6",
                    "Browse local makers, meet artists, and join a small sketching corner.",
                    "Stackt Market",
                    false,
                    85,
                    0,
                    now.AddDays(25).Date.AddHours(23),
                    now.AddDays(26).Date.AddHours(2),
                    EventCategory.Social,
                    "Stackt Market Courtyard",
                    "Toronto",
                    43.6459,
                    -79.3925,
                    ["art", "market", "social"],
                    now.AddDays(-9),
                    now.AddDays(-8)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Cooking Club Potluck #7",
                    "Bring a simple dish, swap recipes, and meet people over a shared meal.",
                    "Community Kitchen",
                    false,
                    95,
                    0,
                    now.AddDays(26).Date.AddHours(18),
                    now.AddDays(26).Date.AddHours(21),
                    EventCategory.Social,
                    "Community Kitchen",
                    "Toronto",
                    43.6474,
                    -79.3938,
                    ["food", "potluck", "social"],
                    now.AddDays(-8),
                    now.AddDays(-7)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Movie Discussion Night #8",
                    "A screening followed by a casual discussion about story, characters, and production.",
                    "Lantern Cinema Room",
                    false,
                    35,
                    0,
                    now.AddDays(27).Date.AddHours(19),
                    now.AddDays(27).Date.AddHours(22),
                    EventCategory.Social,
                    "Lantern Cinema Room",
                    "Toronto",
                    43.6489,
                    -79.3951,
                    ["movie", "discussion", "social"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Rooftop Jazz Evening #9",
                    "Live jazz, mocktails, and relaxed conversation on a downtown rooftop.",
                    "King Street Rooftop",
                    false,
                    45,
                    8,
                    now.AddDays(28).Date.AddHours(20),
                    now.AddDays(28).Date.AddHours(23),
                    EventCategory.Social,
                    "Lantern House Rooftop",
                    "Toronto",
                    43.6504,
                    -79.3964,
                    ["music", "jazz", "rooftop"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Weekend Picnic Meetup #10",
                    "A casual picnic with lawn games and small-group introductions.",
                    "Trinity Bellwoods Park",
                    false,
                    55,
                    0,
                    now.AddDays(29).Date.AddHours(21),
                    now.AddDays(30).Date.AddHours(0),
                    EventCategory.Social,
                    "Trinity Bellwoods Lawn",
                    "Toronto",
                    43.6519,
                    -79.3977,
                    ["picnic", "outdoor", "social"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Board Game Social #11",
                    "A relaxed night of strategy games, party games, snacks, and new friends.",
                    "Lantern House",
                    true,
                    65,
                    0,
                    now.AddDays(30).Date.AddHours(22),
                    now.AddDays(31).Date.AddHours(1),
                    EventCategory.Social,
                    "Lantern House Lounge",
                    "Toronto",
                    43.6459,
                    -79.3925,
                    ["board-games", "social", "indoor"],
                    now.AddDays(-11),
                    now.AddDays(-10)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Karaoke Night #12",
                    "Casual karaoke with group songs, themed rounds, and zero performance pressure.",
                    "Queen West Studio",
                    false,
                    75,
                    0,
                    now.AddDays(31).Date.AddHours(23),
                    now.AddDays(32).Date.AddHours(2),
                    EventCategory.Social,
                    "Queen West Studio",
                    "Toronto",
                    43.6474,
                    -79.3938,
                    ["karaoke", "music", "social"],
                    now.AddDays(-10),
                    now.AddDays(-9)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Photo Walk Meetup #13",
                    "Explore downtown photo spots with prompts for portraits, street scenes, and architecture.",
                    "Nathan Phillips Square",
                    false,
                    85,
                    8,
                    now.AddDays(32).Date.AddHours(18),
                    now.AddDays(32).Date.AddHours(21),
                    EventCategory.Social,
                    "City Hall Plaza",
                    "Toronto",
                    43.6489,
                    -79.3951,
                    ["photography", "walk", "social"],
                    now.AddDays(-9),
                    now.AddDays(-8)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Trivia and Tacos #14",
                    "Team trivia with food, prizes, and rotating categories from movies to tech.",
                    "King Street Loft",
                    false,
                    95,
                    0,
                    now.AddDays(33).Date.AddHours(19),
                    now.AddDays(33).Date.AddHours(22),
                    EventCategory.Social,
                    "King Street Loft",
                    "Toronto",
                    43.6504,
                    -79.3964,
                    ["trivia", "food", "social"],
                    now.AddDays(-8),
                    now.AddDays(-7)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Newcomer Welcome Night #15",
                    "A friendly welcome event for anyone new to the city or the community.",
                    "Lantern House",
                    false,
                    35,
                    0,
                    now.AddDays(34).Date.AddHours(20),
                    now.AddDays(34).Date.AddHours(23),
                    EventCategory.Social,
                    "Lantern House Lounge",
                    "Toronto",
                    43.6519,
                    -79.3977,
                    ["newcomer", "welcome", "social"],
                    now.AddDays(-14),
                    now.AddDays(-13)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Art Market Hangout #16",
                    "Browse local makers, meet artists, and join a small sketching corner.",
                    "Stackt Market",
                    false,
                    45,
                    0,
                    now.AddDays(35).Date.AddHours(21),
                    now.AddDays(36).Date.AddHours(0),
                    EventCategory.Social,
                    "Stackt Market Courtyard",
                    "Toronto",
                    43.6459,
                    -79.3925,
                    ["art", "market", "social"],
                    now.AddDays(-13),
                    now.AddDays(-12)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Cooking Club Potluck #17",
                    "Bring a simple dish, swap recipes, and meet people over a shared meal.",
                    "Community Kitchen",
                    false,
                    55,
                    8,
                    now.AddDays(36).Date.AddHours(22),
                    now.AddDays(37).Date.AddHours(1),
                    EventCategory.Social,
                    "Community Kitchen",
                    "Toronto",
                    43.6474,
                    -79.3938,
                    ["food", "potluck", "social"],
                    now.AddDays(-12),
                    now.AddDays(-11)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Movie Discussion Night #18",
                    "A screening followed by a casual discussion about story, characters, and production.",
                    "Lantern Cinema Room",
                    false,
                    65,
                    0,
                    now.AddDays(37).Date.AddHours(23),
                    now.AddDays(38).Date.AddHours(2),
                    EventCategory.Social,
                    "Lantern Cinema Room",
                    "Toronto",
                    43.6489,
                    -79.3951,
                    ["movie", "discussion", "social"],
                    now.AddDays(-11),
                    now.AddDays(-10)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Rooftop Jazz Evening #19",
                    "Live jazz, mocktails, and relaxed conversation on a downtown rooftop.",
                    "King Street Rooftop",
                    false,
                    75,
                    0,
                    now.AddDays(38).Date.AddHours(18),
                    now.AddDays(38).Date.AddHours(21),
                    EventCategory.Social,
                    "Lantern House Rooftop",
                    "Toronto",
                    43.6504,
                    -79.3964,
                    ["music", "jazz", "rooftop"],
                    now.AddDays(-10),
                    now.AddDays(-9)
                ),
                new SeedEventDefinition(
                    "Lantern Social Collective",
                    "Weekend Picnic Meetup #20",
                    "A casual picnic with lawn games and small-group introductions.",
                    "Trinity Bellwoods Park",
                    false,
                    85,
                    0,
                    now.AddDays(39).Date.AddHours(19),
                    now.AddDays(39).Date.AddHours(22),
                    EventCategory.Social,
                    "Trinity Bellwoods Lawn",
                    "Toronto",
                    43.6519,
                    -79.3977,
                    ["picnic", "outdoor", "social"],
                    now.AddDays(-9),
                    now.AddDays(-8)
                )
            ];
        }

        private static string EventKey(int clubId, string eventName) =>
            $"{clubId}:{eventName}".ToLowerInvariant();

        private sealed record SeedEventDefinition(
            string ClubName,
            string Name,
            string Description,
            string Location,
            bool IsPrivate,
            int MaxParticipants,
            int RegisterCost,
            DateTime StartTimeUtc,
            DateTime? EndTimeUtc,
            EventCategory Category,
            string VenueName,
            string City,
            double Latitude,
            double Longitude,
            IReadOnlyList<string> Tags,
            DateTime CreatedAtUtc,
            DateTime UpdatedAtUtc
        );
    }
}


