namespace backend.main.features.events;

/// <summary>
/// Canonical tag cleanup: trim, lowercase, de-duplicate, cap at ten. Shared so occurrences
/// generated by a series carry tags identical to those a single-event save would produce.
/// </summary>
internal static class EventTagNormalizer
{
    internal const int MaxTags = 10;

    internal static List<string> Normalize(IEnumerable<string>? tags)
    {
        if (tags == null)
            return new List<string>();

        return tags
            .Where(t => !string.IsNullOrWhiteSpace(t))
            .Select(t => t.Trim().ToLowerInvariant())
            .Distinct()
            .Take(MaxTags)
            .ToList();
    }
}
