namespace backend.main.features.events.series;

/// <summary>
/// A repeat rule plus the bookkeeping needed to materialize it into <see cref="Events"/> rows.
/// <para>
/// The schedule is stored as <em>local wall-clock time plus an IANA zone</em>, never as a UTC
/// instant. That is the whole point of the entity: a weekly 7pm series must stay at 7pm local
/// across a DST transition, which is impossible to express by adding a fixed interval to a UTC
/// instant. Occurrences are generated by advancing <see cref="FirstOccurrenceLocalStart"/> in
/// local calendar space and converting each result to UTC individually.
/// </para>
/// </summary>
public class EventSeries
{
    public int Id
    {
        get; set;
    }

    public int ClubId
    {
        get; set;
    }

    /// <summary>
    /// The draft the series was built from, which also becomes occurrence 0.
    /// <para>
    /// Intentionally carries no foreign key. <c>Events.SeriesId</c> already points the other
    /// way, and a second FK back to <c>Events</c> would create two cascade paths between
    /// the same pair of tables, which EF rejects when building the model.
    /// </para>
    /// </summary>
    public int? TemplateEventId
    {
        get; set;
    }

    public EventRecurrenceFrequency Frequency { get; set; } = EventRecurrenceFrequency.Weekly;

    /// <summary>Repeat every N days/weeks/months.</summary>
    public int Interval { get; set; } = 1;

    /// <summary>
    /// Weekly-only day selection, as a bitmask (Sunday = 1 … Saturday = 64). Zero means
    /// "the same weekday as the first occurrence", so the common case needs no input.
    /// </summary>
    public int ByWeekdayMask { get; set; } = 0;

    public EventMonthlyDayPolicy MonthlyDayPolicy { get; set; } = EventMonthlyDayPolicy.ClampToMonthEnd;

    /// <summary>IANA identifier, e.g. <c>Australia/Sydney</c>. Never a Windows zone name.</summary>
    public string TimeZoneId { get; set; } = "UTC";

    /// <summary>
    /// Wall-clock start of occurrence 0, with <see cref="DateTimeKind.Unspecified"/>.
    /// Must never be read as if it were UTC.
    /// </summary>
    public DateTime FirstOccurrenceLocalStart
    {
        get; set;
    }

    /// <summary>
    /// Event length in minutes, applied as an absolute duration to the UTC start. Null means
    /// the occurrences have no end time.
    /// </summary>
    public int? DurationMinutes
    {
        get; set;
    }

    public EventRecurrenceEndMode EndMode { get; set; } = EventRecurrenceEndMode.Count;

    /// <summary>Inclusive local cutoff date when <see cref="EndMode"/> is UntilDate.</summary>
    public DateTime? EndLocalDate
    {
        get; set;
    }

    /// <summary>Total occurrences when <see cref="EndMode"/> is Count.</summary>
    public int? OccurrenceCount
    {
        get; set;
    }

    /// <summary>
    /// High-water mark of occurrence indices already materialized. Lets "extend" resume from
    /// where generation stopped instead of re-creating rows that already exist.
    /// </summary>
    public int GeneratedCount { get; set; } = 0;

    public EventSeriesStatus Status { get; set; } = EventSeriesStatus.Active;

    /// <summary>No FK, mirroring <c>EventVersion.ActorUserId</c>.</summary>
    public int CreatedByUserId
    {
        get; set;
    }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
